### ISSUE TITLE
Inconsistency between API documentation and sandbox for POST /api/v2/messages

### ISSUE THREAD

**Issue by foufure** [textmagic/textmagic-rest-csharp#2]
During the tests of POST /api/v2/messages (send a new outbound message) the question arose which return value it should give back:
- API documentation tells me that it is giving back a "SendingResult" object (see screenshot "sendingresult.png)
- Sandbox tells me that it is giving back a "Pricing" object (see screenshot "pricing.png")

What should be taken? Is the sandbox right? Or does it depend of the return code 201 or 202? (but the sandbox only return 200 OK??).

Can someone clarify this for me?

Thanks in advance!

![pricing](https://cloud.githubusercontent.com/assets/5952085/10003595/6d4e7750-60ad-11e5-82f6-d522f7e40695.png)
![sendingresult](https://cloud.githubusercontent.com/assets/5952085/10003596/6d4fa12a-60ad-11e5-8f4e-095c97784755.png)

**Comment by dmitry-textmagic** [comment]
Hi Jonathan!

POST /api/v2/messages returning _SendingResult_ object unless `dummy` parameter set to `true`. When it happens, it returns _Pricing_ object instead. I.e. GET /api/v2/messages/price is equivalent to POST /api/v2/messages with `dummy = false`. Just a kind of "syntax sugar".

So, in normal situation, POST /api/v2/messages always returns _SendingResult_ with 20x.

**Comment by foufure** [comment]
It is a little bit disappointing to have POST /api/v2/messages returning SendingResult or Pricing which are completely different results. As GET /api/v2/messages/price already provides a mean of simulating the transaction, it is a little bit redundant. If it was for me, I would always return SendingResult and extend it with a Dummy/Real state or let the Dummy completely away.

Please tell me what you think of it. If you do not plan to change something I will close the issue, otherwise I will let it open.

**Comment by dmitry-textmagic** [comment]
I agree with you. We were decided to remove "dummy" parameter from POST /api/v2/messages. I will close this issue when appropriate change become live.

**Comment by dmitry-textmagic** [comment]
This change will be reflected in production tomorrow morning (~6:00 UTC).
