### ISSUE TITLE
Some inconsistencies in sandbox and wrapper API documentation

### ISSUE THREAD

**Issue by foufure** [textmagic/textmagic-rest-csharp#4]
Abbreviations:
[sandbox]: sandbox API documentation refers to https://rest.textmagic.com/api/v2/
[wrapper]: C# Wrapper API documentation refers to https://www.textmagic.com/docs/api/

Search functions are documented in [sandbox] but not in [wrapper].
For all the API functions using PUT the return parameters are documented in [wrapper] but not in sandbox.
For all the API functions using DELETE the return parameters in the [sandbox] are wrong, [wrapper] is right as nothing is returned.

Some examples:
PUT /api/v2/contacts/{id}: return parameters of [sandbox] wrong, [wrapper] right (id / href).
DELETE /api/v2/contacts/{id}: return parameters [sandbox] wrong, [wrapper] right (nothing returned).
GET /api/v2/contacts/{id}/lists: documented in [sandbox] but not in [wrapper].
POST /api/v2/customfields: return parameters not mentioned in [sandbox], but ok in [wrapper].
PUT /api/v2/customfields/{id}: return parameters of [sandbox] wrong, [wrapper] right (id / href).
PUT /api/v2/customfields/{id}/update: return parameters of [sandbox] wrong, [wrapper] right (id / href).
GET /api/v2/unsubscribers: documented in [sandbox] but not in [wrapper].
POST /api/v2/unsubscribers: documented in [sandbox] but not in [wrapper], return (id / href).
GET /api/v2/unsubscribers/{id}: documented in [sandbox] but not in [wrapper].
POST /api/v2/lists: no return parameters in [sandbox], [wrapper] right return (id / href).
POST /api/v2/tokens documented in [sandbox] but not in [wrapper]
GET /api/v2/tokens/refresh documented in [sandbox] but not in [wrapper]
GET /api/v2/ping documented in [sandbox] but not in [wrapper]

**Comment by dmitry-textmagic** [comment]
Partially fixed (will be in production next days).

The main idea was to show in [sandbox] POST/PUT methods linked resource format, not a link format itself (which is documented in [wrapper]).
DELETE /api/v2/contacts/{id} return parameter description fixed.
tokens management feature has been removed.

Documentation for /ping, /unsubscribers and /contacts/{id}/lists will be added soon.
