### ISSUE TITLE
Add Nuget restriction to RestSharp version

### ISSUE THREAD

**Issue by Thorium** [textmagic/textmagic-rest-csharp#7]
When I run automatic package manager update script, it will calculate the dependencies and always ends up to update the RestSharp to incompatible version with textmagic.

This textmagic client is using RestSharp version 105.1.0.
This textmagic client do not work using latest RestSharp version.

So the dependecy in the textmagic Nuget package is wrong: `RestSharp (>= 105.1.0)`
It should also state the largest possible RestSharp-version that do work with textmagic.

**Comment by thinkclay** [comment]
+1 for this

**Comment by dmitry-textmagic** [comment]
TextmagicRest is now depending on exact 105.1.0 version of RestSharp since version 1.0.0;4.

**Comment by awisey** [comment]
Any chance of allowing a greater version of restsharp? my project depends on a greater version than the one textmagic is insisting on
