### ISSUE TITLE
Authenticator appends username and key on every request.

### ISSUE THREAD

**Issue by mcxbe** [textmagic/textmagic-rest-csharp#9]
When I create a client using the `public Client(string username, string token)` signature, the first request works correctly, however the 2nd request returns unauthorized.

This is because the TextmagicAuthenticator appends the username and apikey headers on every request, so when you view your request in something like Wireshark, you can see that the X-TM-Username header has a value of `<my_username>` on the first request, but `<my_username><my_username>` on the 2nd.

**Comment by dmitry-textmagic** [comment]
Could you please provide a code example to reproduce? Please also mention your TextMagicRest and RestSharp versions as well.

**Comment by mcxbe** [comment]
Sorry, this was my fault. I needed .NET core 3.1 support which required me to update to the latest RestSharp. RestSharp 106.11.4 has this behaviour but your listed dependency of RestSharp 105.1.0 works fine.

Closing this issue.
